### ISSUE TITLE
Call to undefined function imagecreatefrompng()

### ISSUE THREAD

**Issue by Coernel82** [fellwell5/bezahlcode#3]
Thank you very much for this quick GDPR-compliant update!
However when running the ` example.php ` I get an error:

`Fatal error: Uncaught Error: Call to undefined function imagecreatefrompng() in F:\xampp-2021\htdocs\bezahlcode\bezahlcode.class.php:115 Stack trace: #0 F:\xampp-2021\htdocs\bezahlcode\bezahlcode.class.php(174): Bezahlcode->getQRCode() #1 F:\xampp-2021\htdocs\bezahlcode\example.php(18): Bezahlcode->generateBase64(Array) #2 {main} thrown in F:\xampp-2021\htdocs\bezahlcode\bezahlcode.class.php on line 115`

Probably no bug just me being a noob? I put all files from the repository into one directory and started the example.php.

What I am trying to do is to improve the Wordpress Onlineshop Plugin WooCommerce with the QR-Code:
[https://github.com/woocommerce/woocommerce/issues/27661](url)

As I am not a programmer I try to gather all the bits and pieces and hope a programmer will commit.

**Comment by Coernel82** [comment]
Found out why:

Please add:
### Prerequisite
php GD2 extension must be installed

**Comment by fellwell5** [comment]
Updated Readme thank you!
